- description: Operator image
  name: IMAGE
  value: quay.io/cloudservices/floorist-operator
- description: Operator image tag
  name: IMAGE_TAG
  value: latest
- description: Floorist exporter tool image
  name: FLOORIST_IMAGE
  value: quay.io/cloudservices/floorist
# Note that the the tag default value is automated
# by GitHub Action
- description: Floorist exporter tool image tag
  name: FLOORIST_IMAGE_TAG
  value: 'be2e435'
